<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Add new Todo using Dashboard</description>
   <name>Create_todo_rock_issues</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3138bc44-7c6d-4768-8941-430004356fa8</testSuiteGuid>
   <testCaseLink>
      <guid>f65d7a70-cae7-45c3-b4db-c4c03964947f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Performance Test/LoginToTractionToolsV2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d216fac2-ebfe-4964-b5ee-c05e557cf0b3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/V2/Performance Test/LoginCredentials-500Users</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d216fac2-ebfe-4964-b5ee-c05e557cf0b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e9bc04f8-765b-4be9-a382-58471bef4f21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d216fac2-ebfe-4964-b5ee-c05e557cf0b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8495d3c6-7081-4110-9f30-8c6e20d18b75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ef5cc9e-34e4-4f81-952b-af697f5ab28c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Performance Test/AddNewToDoUsingDashboard</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6adb5c9e-e155-4d04-a8d9-d13f3a113b8a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/V2/Performance Test/AddNewTodoUsingDashboard</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc4faae7-058a-40a7-800f-60ad76cd345d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b03ed05-9228-4dc6-9666-d6e7ab67cbab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6adb5c9e-e155-4d04-a8d9-d13f3a113b8a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>todo_name</value>
         <variableId>0f98bec3-bd7b-46c0-aaa8-38b70575ea3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7aa3b9-9baa-44a3-8a47-c893a4c93231</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>595f1eae-1a8b-46e1-89a8-d59316c3515b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/V2/Test Case/Performance Test/AddNewRocksUsingDashboard</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6104f3d0-2737-4fdc-b120-5e831f3541ab</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/V2/Performance Test/AddNewRockUsingDashboard</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea02dba3-4efa-4d93-826c-d33f68e1afe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4502e183-3a5f-45cc-b077-be18e8894bea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6104f3d0-2737-4fdc-b120-5e831f3541ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>rock_name</value>
         <variableId>5477fcfc-b447-427b-9ec5-4833ac29c97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dec207fe-0b76-4353-9554-45cff3fc0678</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04f5f202-c2aa-442c-8977-55459aadcf45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/V2/Test Case/Performance Test/AddNewIssueUsingDashboard</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8a6629d5-a782-4119-98da-20677d53486f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/V2/Performance Test/AddNewIssueUsingDashboard</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f52fe2b2-3389-42c9-8b9d-7e67392de23c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8069b3fd-9042-4afc-8d45-cf978ffaafef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8a6629d5-a782-4119-98da-20677d53486f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>issue_name</value>
         <variableId>68d345b1-c78e-447e-b6f1-09c03cb2c553</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
