<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_10</name>
   <tag></tag>
   <elementGuidId>25730810-2b60-40aa-a09b-7095403c0c9c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker__renderedDayContents</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js-focus-visible&quot;]/body[1]/div[8]/div[@class=&quot;SingleDatePicker_picker SingleDatePicker_picker_1 SingleDatePicker_picker__directionRight SingleDatePicker_picker__directionRight_2&quot;]/div[@class=&quot;DayPicker DayPicker_1 DayPicker__horizontal DayPicker__horizontal_2 DayPicker__withBorder DayPicker__withBorder_3&quot;]/div[1]/div[1]/div[@class=&quot;DayPicker_focusRegion DayPicker_focusRegion_1&quot;]/div[@class=&quot;DayPicker_transitionContainer DayPicker_transitionContainer_1 DayPicker_transitionContainer__horizontal DayPicker_transitionContainer__horizontal_2&quot;]/div[@class=&quot;CalendarMonthGrid CalendarMonthGrid_1 CalendarMonthGrid__horizontal CalendarMonthGrid__horizontal_2&quot;]/div[@class=&quot;CalendarMonthGrid_month__horizontal CalendarMonthGrid_month__horizontal_1&quot;]/div[@class=&quot;CalendarMonth CalendarMonth_1&quot;]/table[@class=&quot;CalendarMonth_table CalendarMonth_table_1&quot;]/tbody[1]/tr[2]/td[@class=&quot;CalendarDay CalendarDay_1 CalendarDay__default CalendarDay__default_2&quot;]/div[@class=&quot;datePicker__renderedDayContents&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 2020'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 2020'])[1]/following::div[44]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 2020'])[1]/preceding::div[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td[4]/div</value>
   </webElementXpaths>
</WebElementEntity>
