<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttendeeImage</name>
   <tag></tag>
   <elementGuidId>0e6d6af0-f2c0-4c3b-a5b3-60c8193ae9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='attendees_list']//img[@alt='${username}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='attendees_list']//img[@alt='${username}']</value>
   </webElementProperties>
</WebElementEntity>
