<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Visibility_Level_Field</name>
   <tag></tag>
   <elementGuidId>a35fef96-8528-4457-8a8b-86222a4f8f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'EDIT_ROCK')]//input[@class='search'][@type='text'][contains(@id,'edit-rock')][@name='visibility']/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
