<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ToDo4Checkbox</name>
   <tag></tag>
   <elementGuidId>e70f1400-2bbc-437e-a47e-7f5d2d0c0aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div/div[2]/div[1]/div[2]/div/div[2]/div/div/div[2]/div[4]/div[2]/div/div[1]/label/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
