<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save</name>
   <tag></tag>
   <elementGuidId>38be65e8-65a2-44e5-a26d-13899e3eda49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button']/following-sibling::button[@type='submit'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip_Listener</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;LayoutWrappper-tp58ga-0 TjfAP&quot;]/div[@class=&quot;layout__container&quot;]/div[@class=&quot;layout__content&quot;]/div[@class=&quot;EditMeetingWrapper-sc-1lifrg-4 eAODFB&quot;]/div[@class=&quot;editmeeting__content&quot;]/div[@class=&quot;ScrollShadowStyles-jc1fvm-0 lfIJtz editmeeting__right-column&quot;]/div[@class=&quot;CardStyles-sc-101efrr-0 eKBUFq EditBasicInfoWrapper-sc-1qtq3xf-12 joMSAE&quot;]/div[@class=&quot;CardBodyStyles-sc-101efrr-1 gLgRZi card__body _StyledCardBody-sc-1qtq3xf-1 ibgTre&quot;]/form[1]/div[@class=&quot;_StyledDiv11-sc-1qtq3xf-11 gDXNac editbasic__content&quot;]/button[@class=&quot;BtnTextStyles-mkwxlk-0 jRTTNs&quot;]/div[@class=&quot;tooltip_Listener&quot;]</value>
   </webElementProperties>
</WebElementEntity>
