<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Go to meeting_IconStyles-sc-181ai5j-0 fsp_3689c0</name>
   <tag></tag>
   <elementGuidId>5de20196-bdbc-4a58-8f1a-c2278dc7dc38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IconStyles-sc-181ai5j-0 fspyWU icon-more-vertical naked__icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;LayoutWrappper-tp58ga-0 bOckMl&quot;]/div[@class=&quot;layout__container false&quot;]/div[@class=&quot;layout__content&quot;]/div[@class=&quot;MeetingsWrapper-sc-5wv2fa-3 iXSCWL&quot;]/div[1]/div[@class=&quot;_StyledDiv11-zxhscp-11 bNSzRo page__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ListContainer-sc-168y9zd-1 eAUniv&quot;]/div[@class=&quot;listcontainer__options&quot;]/button[@class=&quot;BtnIconNakedStyles-sc-1vxkzkz-0 hDvyIS option-button&quot;]/i[@class=&quot;IconStyles-sc-181ai5j-0 fspyWU icon-more-vertical naked__icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
   </webElementXpaths>
</WebElementEntity>
