<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Goal_Direction_Number_Between</name>
   <tag></tag>
   <elementGuidId>ef53ac7d-c0dc-41e0-90da-aa13f7927ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CREATE_MEASURABLE']/div[2]/div/div/form/div[2]/div[2]/div/div/div/div[2]/div[6]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
