<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selected_Unit_Field_Hour</name>
   <tag></tag>
   <elementGuidId>3aca8e14-81c7-4977-9142-b34335e99504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CREATE_MEASURABLE']/div[2]/div/div/form/div[3]/div/div/div/div/div[2]/div[7]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
