<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create_Headline_Button</name>
   <tag></tag>
   <elementGuidId>22e1409b-d7f3-4754-9b0b-db196b27dc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='createActions']//button[@data-test-id='createActions.peopleHeadline'][contains(@class,'ItemButton-sc')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
