<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Headline_Title</name>
   <tag></tag>
   <elementGuidId>be27ae7e-bcc6-4e1d-916b-8889fa24c395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='createPeopleHeadline']//div[@data-test-id='peopleHeadline.title']/input[contains(@id,'createPeopleHeadline')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
