<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done_Status_Checkbox</name>
   <tag></tag>
   <elementGuidId>5ee70470-0193-4533-aa39-9d3c04c828d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> //input[@id='CREATE_TODO-done'][@type='checkbox']/parent::div[@class='tooltip_Listener']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IconStyles-sc-181ai5j-0 fspyWU icon-checkbox checkbox__icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-root&quot;)/div[@id=&quot;CREATE_TODO&quot;]/div[@id=&quot;CREATE_TODO&quot;]/form[1]/div[@class=&quot;panel__header&quot;]/div[@class=&quot;panel__headerInner&quot;]/div[@class=&quot;StackStyles-sc-12tx3af-1 iXXrsT stack&quot;]/div[@class=&quot;ItemStyles-sc-12tx3af-0 jpgAxN stack__item&quot;]/label[@class=&quot;CheckboxStyles-v6t393-0 dntwbe&quot;]/div[@class=&quot;tooltip_Listener&quot;]/i[@class=&quot;IconStyles-sc-181ai5j-0 fspyWU icon-checkbox checkbox__icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CREATE_TODO']/form/div/div/div/div[2]/label/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/label/div/i</value>
   </webElementXpaths>
</WebElementEntity>
