<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create_ToDo_Button</name>
   <tag></tag>
   <elementGuidId>daf3491a-8262-49fe-a570-05fe66446883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='createActions']//button[@data-test-id='createActions.todo'][contains(@class,'ItemButton-sc')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
