<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ToDo_Title</name>
   <tag></tag>
   <elementGuidId>a5c770f9-6b4c-4059-bdbe-f0bc391a822c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='createTodo']//div[@data-test-id='todo.title']/input[contains(@id,'createTodo')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
