<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VTO_NameTitle</name>
   <tag></tag>
   <elementGuidId>a1cb086c-7a34-43a9-a3dc-6555cd4f2785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@data-test-id='vto.name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Test</name>
      <type>Main</type>
      <value>//div[@class='ItemStyles-sc-12tx3af-0 jPsruz stack__item']//div[@class='TextBodyStyles-sc-2kprof-0 iQaIOf']//span[@class='vtoInput__control']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>asdfadsfas</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>asdf</value>
   </webElementXpaths>
</WebElementEntity>
