<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done_CheckBox</name>
   <tag></tag>
   <elementGuidId>69f04f13-d4fe-4b87-a29b-29ecadbf2cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='editRock']//input[contains(@id,'milestone-done-edit-rock')][contains(@name,'milestone-done-edit-rock')]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
