<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GeneralBasic informationVideo conferenc_ee1ae7</name>
   <tag></tag>
   <elementGuidId>0fb0356f-a0db-4215-8a02-882650337190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editmeeting__content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GeneralBasic informationVideo conferenceAttendeesUsers and permissionsGeneralBasic informationMeeting name *Acronym *Meeting description (max 100 characters) Type of meeting *LeadershipLeadershipDepartmentalSame PageBoardOwner'sOtherMeeting color *Day of meeting *MondayMondayTuesdayWednesdayThursdayFridaySaturdaySundayTime *am8:00am/pm12:00am/pm1:00am/pm2:00am/pm3:00am/pm4:00am/pm5:00am/pm6:00am/pm7:00am/pm8:00am/pm9:00am/pm10:00am/pm11:00amDuration (minutes)90CancelSaveVideo conferenceWorking remote with your team? Add your preferred video conference URL to connect with your team online.Video conference URL CancelSaveAttendeesUsers and permissionsPermissions breakdown:Meeting admin (recommended for meeting leader)Can view, create and edit all meeting content. Can access and change settings for meeting.Full editorCan view and edit all meeting content.Basic editorCan view all meeting content but only edit their items.Add Users Start typing employee's name or select from the drop-downjeffrey012Supervisor mazo2jeffrey013Employee Mazo3jeffrey014Employee2 Mazo4Add usersNamesPermissionsJeffrey011Admin MazoAdminAdminFull editorBasic editor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;LayoutWrappper-tp58ga-0 TjfAP&quot;]/div[@class=&quot;layout__container&quot;]/div[@class=&quot;layout__content&quot;]/div[@class=&quot;EditMeetingWrapper-sc-1lifrg-4 eAODFB&quot;]/div[@class=&quot;editmeeting__content&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASDFF'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit meeting:'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
