<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accountable_Owner_FieldButton</name>
   <tag></tag>
   <elementGuidId>99b6e714-d16f-4894-9bba-064e76477ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'createTodo')]//input[@name='assigneeId']/parent::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='panel-root']/div[@id='createTodo-65e0107e-e0f9-4389-9a32-56b4ed1d59ae']/div[@id='createTodo-65e0107e-e0f9-4389-9a32-56b4ed1d59ae']/form/div[@class='panel__body']/div[@class='ScrollShadowStyles-jc1fvm-0 lfIJtz panel__scrollShadow']/div[@class='panel__bodyInner']/div[2]/div[1]/div[1]/div[1]/button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[4]/div[2]/form[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]</value>
   </webElementXpaths>
</WebElementEntity>
