<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmCompanyInfo_NumberOfEmployees</name>
   <tag></tag>
   <elementGuidId>10259eb4-8595-46c8-8c46-813aba445785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;FIRST_INFO_UPDATE_MODAL&quot;]/div[2]/div/div/div/form/div[4]/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
