<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumberOfEmployeesOption1</name>
   <tag></tag>
   <elementGuidId>25983718-08f4-4705-a188-ce9779b2a71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;FIRST_INFO_UPDATE_MODAL&quot;]/div[2]/div/div/div/form/div[4]/div[2]/div/div/div/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
