<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ScorecardHighlightCurrentWeek</name>
   <tag></tag>
   <elementGuidId>9de5ed1b-8ec5-48b1-8523-98278bda4bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/form/div[1]/div[2]/div/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
