<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WeekStartTuesday</name>
   <tag></tag>
   <elementGuidId>4318c3e2-1b3b-486e-91bc-b4bc3378f3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/form/div[1]/div[1]/div/div/div/div[2]/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
