<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Goal_Type_Field_Workspace</name>
   <tag></tag>
   <elementGuidId>893b06a6-dd2a-41a2-9b21-34f4e1f60032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'EDIT_MEASURABLE')]//input[@class='search'][@name='goalType']/parent::div[@role='combobox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
