<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login</name>
   <tag></tag>
   <elementGuidId>46c48e20-9785-462e-b104-5c2d46a32b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[1]/div[2]/div/form/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip_Listener</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;AuthLayoutContainer-sc-1es7eb7-2 jwViYx&quot;]/div[@class=&quot;AuthLayoutContent-sc-1es7eb7-3 xZHHm&quot;]/div[@class=&quot;StyledContainer-hqrtyo-0 Qytui&quot;]/div[@class=&quot;LoginFormContainer-iro59q-0 eUNpUs&quot;]/form[1]/button[@class=&quot;BtnTextStyles-mkwxlk-0 fCpDYU _StyledBtnText-iro59q-3 hKZnud&quot;]/div[@class=&quot;tooltip_Listener&quot;]</value>
   </webElementProperties>
</WebElementEntity>
