<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Admin_Access_TextField_Workspace</name>
   <tag></tag>
   <elementGuidId>022d367c-b9b8-413f-a9a3-9522691de28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'createMeasurable')]//input[@id='createMeasurable-adminId'][@name='adminId']/parent::div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
