<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Whosaccountable_TextField_Workspace</name>
   <tag></tag>
   <elementGuidId>41f3a9be-4d21-4e93-a883-3ccaaadb7a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'createMeasurable')]//input[@id='createMeasurable-assigneeId'][@name='assigneeId']/parent::div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
