<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Visibility_Level_Individual</name>
   <tag></tag>
   <elementGuidId>ffbdb8bb-1fae-4df7-9c74-f80183c9183f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CREATE_ROCK']/div[2]/div/div/form/div/div[3]/div/div/div/div/div[2]/div[3]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
