<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TT-167_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5f3f10ef-5797-4317-a23d-469206d914f1</testSuiteGuid>
   <testCaseLink>
      <guid>3ffb35b2-1c21-4f5e-9a6d-fbb0202ee62b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_1_EditUser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>79f7a4a5-a8c8-4f28-8479-fe2160088072</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_2_AddUserWithoutSendInvite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df331ed9-7dd2-4df7-b8dc-167fd78487da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1485dab-7d4f-4d6b-9f0b-dc79d83ac2ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33027cb3-52ca-4c9a-87e3-5e4085f6fcc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>947e2983-31da-4b80-911b-787ec183a410</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35cd9784-1f04-4bfe-b1ff-d430aa5eadba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_3_AddUserWithSendInvite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2891feb7-a511-4a2a-85cd-e800111fe23b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a75327b9-475c-4b26-8e3f-15f7ae87b506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fa628d6-b65e-41a7-8b49-0c3919d3b944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ce66256-5cbe-4caf-8af1-65e7fa60832e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5493da09-a572-4b9b-b736-3c3f5b2ff569</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_4_ArchiveUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71addadb-97fe-40ab-89d1-bf55373e08ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa7b24ba-f6a3-4453-be07-7de90b718e76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e6299f5-be6a-459c-9703-adaadd2639b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff685518-cfef-4e0c-b6f2-d649a92f8a23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0dc28dd5-3341-4c7c-9867-9ab312b2d25e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_5_UnarchiveUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4d4db6-b8dd-497a-8052-65e202aee20c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9432bd0f-00ef-47c6-af06-4bd2e3c42f59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4984ad93-136f-4ba4-aa36-d8faa1cae2e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec36b91-c784-4789-9c55-f9372899a3d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e9c7ef1-3be3-453d-9662-2226f2ee2748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/V2/Test Case/Tests/TT-167 - Manage User/Positive/TT_167_6_ViewProfile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc51eafe-b8c9-4870-bee8-20b5e4054326</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b84ecdb-8eca-4eaa-957d-eb1e612df6b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b03e7b6-186f-459b-86e1-b0e5c729ec02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b92db166-6624-4fd9-93d4-3f4d863cdf0a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
