<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Quarterly Printout_switchInput__slider</name>
   <tag></tag>
   <elementGuidId>9cb7af58-19c9-4ae3-a105-0db4b84c0e94</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switchInput__slider</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@id=&quot;meetinglist-printout-modal-cf42d054-28c3-4238-ba39-ee3e7af4841b&quot;]/div[@id=&quot;meetinglist-printout-modal-cf42d054-28c3-4238-ba39-ee3e7af4841b&quot;]/div[@class=&quot;modal__wrapper&quot;]/div[@class=&quot;modal__body&quot;]/div[@class=&quot;ScrollShadowStyles-jc1fvm-0 lfIJtz modal__scrollShadow&quot;]/div[@class=&quot;modal__bodyInner&quot;]/div[@class=&quot;_StyledDiv-sc-13kbs61-1 fqUBP&quot;]/div[@class=&quot;_StyledDiv2-sc-13kbs61-2 hIRqJm&quot;]/label[@class=&quot;SwitchInputStyles-sc-17lxekm-0 ePuJkg&quot;]/div[@class=&quot;tooltip_Listener&quot;]/span[@class=&quot;switchInput__track&quot;]/span[@class=&quot;switchInput__slider&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='meetinglist-printout-modal-cf42d054-28c3-4238-ba39-ee3e7af4841b']/div[2]/div[2]/div/div/div/div/label/div/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
   </webElementXpaths>
</WebElementEntity>
